# Generated by Django 5.0.3 on 2024-03-14 16:39

import app.validations
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Condomínio')),
                ('ddd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)], verbose_name='DDD')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.BooleanField(verbose_name='É Whatsapp?')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('qtd_habitacional', models.PositiveIntegerField(verbose_name='Unidades habitacionais serão atendidas')),
                ('primeira_coleta', models.DateField(verbose_name='Data da primeira coleta')),
                ('turno', models.CharField(choices=[('0', 'Manhã(09:00 às 11:30)'), ('1', 'Tarde(13:40 às 16:30)'), ('2', 'Não tenho preferência')], max_length=100, verbose_name='Turno de preferência')),
                ('tipo_pix', models.CharField(choices=[('0', 'CPF ou CNPJ'), ('1', 'Email'), ('2', 'Número telefônico'), ('3', 'Chave Aleatória')], max_length=50, verbose_name='Tipo de chave pix')),
                ('chave_pix', models.CharField(max_length=300, verbose_name='Chave pix')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('indicacao', models.CharField(choices=[('0', 'Indicação'), ('1', 'Instagram Prefeitura de Fortaleza'), ('2', 'Através de um agente ambiental(Mais Fortaleza)'), ('3', 'Comunicação oficial da Prefeitura'), ('4', 'Recebi um planfeto do Recicla +')], max_length=200, verbose_name='Onde conheceu o Recicla+?')),
                ('responsavel', models.CharField(choices=[('0', 'Síndico'), ('1', 'Empresa')], max_length=100, verbose_name='Tipo de Responsável')),
                ('nome_responsavel', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('cpf_responsavel', models.CharField(blank=True, max_length=30, null=True, unique='True', validators=[app.validations.validate_CPF], verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, unique='True', validators=[app.validations.validate_CNPJ], verbose_name='CPF')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('ponto_referencia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ponto de referência')),
                ('identificador', models.IntegerField(default=0, verbose_name='Identificador')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
            },
        ),
    ]
