# Generated by Django 5.0.3 on 2024-03-14 16:50

import app.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='cnpj_condominio',
            field=models.CharField(max_length=30, null=True, unique='True', validators=[app.validations.validate_CNPJ], verbose_name='CNPJ Condimínio'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, unique='True', validators=[app.validations.validate_CNPJ], verbose_name='CNPJ Responsável'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=30, null=True, unique='True', validators=[app.validations.validate_CPF], verbose_name='CPF Responsável'),
        ),
    ]
