# Generated by Django 5.0.3 on 2024-03-14 18:13

import app.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_condominio_cnpj_condominio_alter_condominio_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='cnpj_condominio',
            field=models.CharField(max_length=30, null=True, unique='True', validators=[app.validations.validate_CNPJ], verbose_name='CNPJ Condomínio'),
        ),
    ]
