# Generated by Django 5.0.3 on 2024-03-15 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_condominio_cnpj_condominio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('pergunta', models.CharField(max_length=150, verbose_name='Pergunta')),
                ('resposta', models.CharField(max_length=150, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Duvida',
                'verbose_name_plural': 'Duvidas',
            },
        ),
    ]
