# Generated by Django 5.0.3 on 2024-03-15 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_duvida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=50, verbose_name='Parceiro')),
                ('imagem', models.ImageField(upload_to='parceiros/', verbose_name='Imagem')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
