# Generated by Django 5.0.3 on 2024-03-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_parceiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='cpf_responsavel',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='primeira_coleta',
        ),
        migrations.AddField(
            model_name='condominio',
            name='contato_responsavel',
            field=models.CharField(max_length=20, null=True, verbose_name='Contato do Responsável'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='dias_semana',
            field=models.CharField(max_length=10, null=True, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='zelador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Zelador'),
        ),
    ]
