# Generated by Django 5.0.3 on 2024-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_condominio_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='bonificacao',
            field=models.CharField(choices=[('0', 'Sim'), ('0', 'Não, aceito que o valor seja revertido para os catadores de Fortaleza')], max_length=50, null=True, verbose_name='Bonificação'),
        ),
    ]
