# Generated by Django 5.0.3 on 2024-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_condominio_turno_alter_condominio_bonificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='cnpj_condominio',
            field=models.CharField(max_length=30, null=True, unique='True', verbose_name='CNPJ Condomínio'),
        ),
    ]
