# Generated by Django 5.0.3 on 2024-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_condominio_cnpj_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='zelador',
        ),
        migrations.AlterField(
            model_name='condominio',
            name='bonificacao',
            field=models.CharField(choices=[('0', 'Desejo participar do programa de bonificação'), ('1', 'Desejo doar os recicláveis para associações de catadores abrindo mão da bonificação')], max_length=50, null=True, verbose_name='Bonificação'),
        ),
    ]
